service: serverless-lambda

plugins:
  - 'serverless-bundle'
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, env:STAGE, 'develop'}
  serverless-offline:
    httpPort: 3333
    lambdaPort: 2333
    noPrependStageInUrl: true
  bundle:
    linting: false
    tsConfig: 'tsconfig.app.json'

params:
  production:
    production: true
  develop:
    production: false

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${self:custom.stage}
  endpointType: REGIONAL
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps

functions:
  foo:
    handler: src/handlers/foo.handler
    events:
      - http:
          method: GET
          path: /foo
