name: _Reusable protect stage

on:
  workflow_call:
    inputs:
      stage:
        required: true
        type: string
      protection:
        required: true
        type: string
    outputs:
      stage:
        value: ${{ jobs.check.outputs.stage }}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      stage: ${{ steps.stage.outputs.stage }}
    steps:

      - name: Check stage
        run: |

          if [[ ${{ inputs.stage }} == 'production' && ${{ inputs.protection }} != 'production' ]]; then
            echo "Production deployment can not be without protection rule!"
            exit 1
          fi
