name: Deploy ecs task

run-name: ${{ github.workflow }} "${{ inputs.app }}" from branch ${{ inputs.branch || github.ref_name }} to stage ${{ inputs.stage }}, [tests - ${{ inputs.tests }}]

on:
  workflow_dispatch:
    inputs:
      app:
        type: choice
        description: "Ecs app to deploy"
        required: true
        default: ecs-task
        options:
          - ecs-task
      stage:
        type: choice
        description: "Stage to deploy"
        required: true
        default: develop
        options:
          - develop
          - production
      tests:
        type: boolean
        description: "Run tests?"
        default: true
        required: true
      protection:
        description: "Write production to deploy from master to production"
        required: true
        default: "not-production"
      branch:
        description: "Branch, Tag or SHA to checkout *(optional)"
        required: false

jobs:
  stage:
    uses: ./.github/workflows/_reusable-protect-stage.yml
    with:
      stage: ${{ inputs.stage }}
      protection: ${{ inputs.protection }}

  deploy:
    needs: stage
    uses: ./.github/workflows/_reusable-deploy-ecs-task.yml
    with:
      app: ${{ inputs.app }}
      stage: ${{ inputs.stage }}
      tests: ${{ inputs.tests }}
    secrets: inherit
