name: Deploy client

run-name: ${{ github.workflow }} from branch ${{ inputs.branch || github.ref_name }} to stage ${{ inputs.stage }}, [tests - ${{ inputs.tests }}]

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: "Stage to deploy"
        required: true
        default: develop
        options:
          - develop
          - production
      tests:
        type: boolean
        description: "Run tests?"
        default: true
        required: true
      protection:
        description: "Write production to deploy from master to production"
        required: true
        default: "not-production"
      branch:
        description: "Branch, Tag or SHA to checkout *(optional)"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.stage }}

jobs:
  stage:
    uses: ./.github/workflows/_reusable-protect-stage.yml
    with:
      stage: ${{ inputs.stage }}
      protection: ${{ inputs.protection }}

  client:
    needs: stage
    uses: ./.github/workflows/_reusable-deploy-client.yml
    with:
      app: client
      stage: ${{ inputs.stage }}
      tests: ${{ inputs.tests }}
    secrets: inherit
