name: Destroy AWS infra

run-name: ${{ github.workflow }} on stage ${{ inputs.stage }} from branch ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      stage:
        type: choice
        description: "Stage to destroy"
        required: true
        default: develop
        options:
          - develop
          - production
      protection:
        description: "Write production to destroy production from master"
        required: true
        default: "not-production"
jobs:
  stage:
    uses: ./.github/workflows/_reusable-protect-stage.yml
    with:
      event_name: ${{ github.event_name }}
      stage: ${{ inputs.stage }}
      protection: ${{ inputs.protection }}

  destroy:
    needs: stage
    uses: ./.github/workflows/_reusable-deploy-cdk.yml
    with:
      stage: ${{ inputs.stage }}
      destroy: true
    secrets: inherit
